In [5]:
import numpy as np
x=np.array([[[1],[2]],[[3],[4]]])
print(x.shape)

(2, 2, 1)


In [6]:
print(x)

[[[1]
  [2]]

 [[3]
  [4]]]


In [8]:
a=np.random.randn(2,3)
a.shape=(2,3)

In [9]:
b=np.random.randn(2,1)
b.shape=(2,1)

In [10]:
c = a + b

In [11]:
print(c.shape)

(2, 3)


In [12]:
a=np.random.randn(4,3)
a.shape=(4,3)

In [13]:
b=np.random.randn(1,3)
b.shape=(1,3)

In [17]:
c = a * b

In [18]:
print(c.shape)

(4, 3)


In [19]:
a=np.array([[2,1],[1,3]])
a = np.dot(a, a)
print(a)

[[ 5  5]
 [ 5 10]]


In [24]:
a.shape=(4,3)
b.shape=(4,1)
for i in range(3):
    for j in range(4):
        c[i][j] = a[j][i] + b[j]
print(c(a + b))

ValueError: cannot reshape array of size 4 into shape (4,3)