In [1]:
import numpy as np

a = np.random.randn(5)

In [2]:
print(a)

[-1.0428667  -1.19565568 -1.42067171  0.89460447 -1.37683759]


In [3]:
print(a.shape)

(5,)


In [4]:
print(a.T)

[-1.0428667  -1.19565568 -1.42067171  0.89460447 -1.37683759]


In [5]:
print(np.dot(a, a.T))

7.231470441949658


### When you are coding new networks, don't use data structures where the shape is n, (n comma) just like our example above 5, (5 comma)

### Instead you can commit a to be a 5 x 1 column vector (5, 1)

In [6]:
# Column vector. (1,5) vector is a row vector
a = np.random.randn(5, 1)
print(a)

[[ 0.41018597]
 [-0.84319874]
 [-1.16192826]
 [ 1.69306736]
 [-0.50927486]]


In [7]:
print(a.T)

[[ 0.41018597 -0.84319874 -1.16192826  1.69306736 -0.50927486]]


In [8]:
print(np.dot(a, a.T))

[[ 0.16825253 -0.34586829 -0.47660666  0.69447247 -0.2088974 ]
 [-0.34586829  0.71098411  0.97973644 -1.42759226  0.42941992]
 [-0.47660666  0.97973644  1.35007728 -1.96722281  0.59174086]
 [ 0.69447247 -1.42759226 -1.96722281  2.86647708 -0.86223665]
 [-0.2088974   0.42941992  0.59174086 -0.86223665  0.25936089]]


In [9]:
b = np.random.rand(1, 5)
print(b)

[[0.28904321 0.59220806 0.56883558 0.00487702 0.65428731]]


In [13]:
# asserting that my variable is a vector
assert(a.shape == (5,1))