In [5]:
import numpy as np

a=np.random.randn(3,3)
b=np.random.randn(3,1)
c= a * b

print(c)

[[ 0.03491723 -0.00257037 -0.03264897]
 [-0.1661348   0.24984914  0.00167662]
 [ 0.63998718 -0.93107921  0.72992869]]


In [4]:
print(c.shape)

(3, 3)


In [15]:
a=np.array([[2,1],[1,3]])
print(a * a)

[[4 1]
 [1 9]]


In [22]:
a=np.random.randn(4,3)
a.shape = (4, 3)
print(a)
b=np.random.randn(3,2)
b.shape = (3, 2)
print(b)

[[-1.36551585  0.49468825 -0.31314935]
 [ 1.52659039 -0.09624531  0.00950271]
 [ 0.20660898 -0.81364042 -0.68349771]
 [-0.82743951 -2.57051893  0.86404977]]
[[-2.1117929  -1.60521331]
 [-0.03113919  1.93836969]
 [-0.90138204 -0.98815241]]


In [21]:
c = a * b
print(c.shape)

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [23]:
a=np.random.randn(3,3)
a.shape=(3,3)
print(a)

b=np.random.randn(2,1)
b.shape=(2,1)
print(b)

[[-0.38648792  0.69923887  1.14559487]
 [-0.73826909  3.10118536 -0.78421489]
 [-0.85556779 -0.3534891  -0.69076701]]
[[0.5438406 ]
 [0.92966678]]


In [24]:
c = a + b
print(c)
print(c.shape)

ValueError: operands could not be broadcast together with shapes (3,3) (2,1) 

In [25]:
x=np.array([[[1],[2]],[[3],[4]]])
print(x)
print(x.shape)

[[[1]
  [2]]

 [[3]
  [4]]]
(2, 2, 1)


In [30]:
a=np.random.randn(2,3)
a.shape=(2,3)

b=np.random.randn(2,1)
b.shape=(2,1)

c=a+b
print(c.shape)

(2, 3)


In [31]:
a=np.random.randn(4,3)
a.shape=(4,3)

b=np.random.randn(1,3)
b.shape=(1,3)

c= a * b
print(c.shape)

(4, 3)


In [33]:
a=np.array([[2,1],[1,3]])
result = np.dot(a, a)
print(result)

[[ 5  5]
 [ 5 10]]


In [53]:
a = np.random.randn(3,3)
a.shape=(3,3)

b=np.random.randn(3,3)
b.shape=(3,3)

c= a**2 + b.T**2
print(c)

[[ 2.80659871 10.02072313  0.25633408]
 [ 0.68583508  1.2200956   1.00208653]
 [ 1.81584482  0.22845909  1.83949516]]


In [54]:

'''
for i in range(3):
    for j in range(3):
        c[i][j] = a[i][j]**2 + b[i][j]**2
print(c)
'''

for i in range(3):
    for j in range(3):
        c[i][j] = a[i][j]**2 + b[j][i]**2
print(c)


'''
for i in range(3):
    c[i] = a[i]**2 + b[i]**2
print(c)
'''

[[ 2.80659871 10.02072313  0.25633408]
 [ 0.68583508  1.2200956   1.00208653]
 [ 1.81584482  0.22845909  1.83949516]]


'\nfor i in range(3):\n    c[i] = a[i]**2 + b[i]**2\nprint(c)\n'